"""Wbudowana lista konkretnych produktów z markami — fallback gdy OFF search niedostępny."""

PRODUKTY: list[dict] = [
    # ── Nabiał ────────────────────────────────────────────────────────────────
    {"name": "Mleko 2% Mlekovita", "category": "nabiał"},
    {"name": "Mleko 3,2% Mlekovita", "category": "nabiał"},
    {"name": "Mleko UHT 2% Łaciate", "category": "nabiał"},
    {"name": "Mleko UHT 3,2% Łaciate", "category": "nabiał"},
    {"name": "Mleko 2% Piątnica", "category": "nabiał"},
    {"name": "Mleko skondensowane Gostyń", "category": "nabiał"},
    {"name": "Masło extra Łaciate", "category": "nabiał"},
    {"name": "Masło President 82%", "category": "nabiał"},
    {"name": "Masło Mlekovita 82%", "category": "nabiał"},
    {"name": "Ser Gouda plastry Mlekovita", "category": "nabiał"},
    {"name": "Ser Edamer plastry Piątnica", "category": "nabiał"},
    {"name": "Ser Edam Hochland", "category": "nabiał"},
    {"name": "Ser Gouda Wieluński", "category": "nabiał"},
    {"name": "Serek Almette śmietankowy Hochland", "category": "nabiał"},
    {"name": "Serek wiejski Piątnica", "category": "nabiał"},
    {"name": "Twaróg półtłusty Piątnica", "category": "nabiał"},
    {"name": "Twaróg chudy Łaciate", "category": "nabiał"},
    {"name": "Jogurt naturalny Activia Danone", "category": "nabiał"},
    {"name": "Jogurt naturalny Piątnica", "category": "nabiał"},
    {"name": "Jogurt truskawkowy Zott Monte", "category": "nabiał"},
    {"name": "Jogurt owocowy Bakoma", "category": "nabiał"},
    {"name": "Jogurt grecki Epiros", "category": "nabiał"},
    {"name": "Śmietana 18% Mlekovita", "category": "nabiał"},
    {"name": "Śmietana 30% Piątnica", "category": "nabiał"},
    {"name": "Śmietanka do kawy 12% Łaciate", "category": "nabiał"},
    {"name": "Kefir naturalny Piątnica", "category": "nabiał"},
    {"name": "Maślanka pitna Mlekovita", "category": "nabiał"},
    {"name": "Mozzarella Galbani", "category": "nabiał"},
    {"name": "Ser Brie President", "category": "nabiał"},
    {"name": "Ser Camembert Bongrain", "category": "nabiał"},
    {"name": "Ser feta Apetina", "category": "nabiał"},
    {"name": "Ricotta Galbani", "category": "nabiał"},
    {"name": "Parmezan Grana Padano", "category": "nabiał"},

    # ── Mięso ─────────────────────────────────────────────────────────────────
    {"name": "Pierś z kurczaka Drosed", "category": "mięso surowe"},
    {"name": "Filet z kurczaka Gobarto", "category": "mięso surowe"},
    {"name": "Udka z kurczaka Drosed", "category": "mięso surowe"},
    {"name": "Skrzydełka kurczaka Gobarto", "category": "mięso surowe"},
    {"name": "Mielone wieprzowe Sokołów", "category": "mięso surowe"},
    {"name": "Mielone wołowe Sokołów", "category": "mięso surowe"},
    {"name": "Schab bez kości Morliny", "category": "mięso surowe"},
    {"name": "Boczek wędzony Sokołów", "category": "mięso surowe"},
    {"name": "Szynka gotowana Sokołów", "category": "mięso surowe"},
    {"name": "Szynka wieprzowa Morliny", "category": "mięso surowe"},
    {"name": "Kiełbasa śląska Sokołów", "category": "mięso surowe"},
    {"name": "Kiełbasa krakowska Morliny", "category": "mięso surowe"},
    {"name": "Kabanosy Morliny", "category": "mięso surowe"},
    {"name": "Parówki drobiowe Sokołów", "category": "mięso surowe"},
    {"name": "Parówki wieprzowe Morliny", "category": "mięso surowe"},
    {"name": "Filet z indyka Animex", "category": "mięso surowe"},
    {"name": "Karkówka wieprzowa", "category": "mięso surowe"},
    {"name": "Żeberka wieprzowe", "category": "mięso surowe"},
    {"name": "Polędwica wołowa", "category": "mięso surowe"},

    # ── Ryby ──────────────────────────────────────────────────────────────────
    {"name": "Łosoś filet norweski", "category": "ryby"},
    {"name": "Dorsz filet mrożony", "category": "ryby"},
    {"name": "Pstrąg tęczowy", "category": "ryby"},
    {"name": "Makrela wędzona", "category": "ryby"},
    {"name": "Śledź w oleju Lisner", "category": "ryby"},
    {"name": "Śledź w śmietanie Lisner", "category": "ryby"},
    {"name": "Tuńczyk w sosie własnym Graal", "category": "przetwory"},
    {"name": "Tuńczyk w oleju Rio Mare", "category": "przetwory"},
    {"name": "Szprot w oleju Łosoś", "category": "przetwory"},
    {"name": "Sardynki w oleju", "category": "przetwory"},

    # ── Warzywa twarde ────────────────────────────────────────────────────────
    {"name": "Ziemniaki", "category": "warzywa twarde"},
    {"name": "Marchewka", "category": "warzywa twarde"},
    {"name": "Cebula", "category": "warzywa twarde"},
    {"name": "Czosnek", "category": "warzywa twarde"},
    {"name": "Papryka czerwona", "category": "warzywa twarde"},
    {"name": "Papryka żółta", "category": "warzywa twarde"},
    {"name": "Papryka zielona", "category": "warzywa twarde"},
    {"name": "Ogórek zielony", "category": "warzywa twarde"},
    {"name": "Pomidor", "category": "warzywa twarde"},
    {"name": "Brokuły", "category": "warzywa twarde"},
    {"name": "Kalafior", "category": "warzywa twarde"},
    {"name": "Kapusta biała", "category": "warzywa twarde"},
    {"name": "Kapusta pekińska", "category": "warzywa twarde"},
    {"name": "Buraki", "category": "warzywa twarde"},
    {"name": "Cukinia", "category": "warzywa twarde"},
    {"name": "Bakłażan", "category": "warzywa twarde"},
    {"name": "Por", "category": "warzywa twarde"},
    {"name": "Seler naciowy", "category": "warzywa twarde"},
    {"name": "Pieczarki", "category": "warzywa twarde"},

    # ── Warzywa liściaste ─────────────────────────────────────────────────────
    {"name": "Sałata lodowa", "category": "warzywa liściaste"},
    {"name": "Szpinak baby", "category": "warzywa liściaste"},
    {"name": "Rukola", "category": "warzywa liściaste"},
    {"name": "Mix sałat", "category": "warzywa liściaste"},

    # ── Owoce ─────────────────────────────────────────────────────────────────
    {"name": "Jabłka Gala", "category": "owoce"},
    {"name": "Jabłka Jonagold", "category": "owoce"},
    {"name": "Banany", "category": "owoce"},
    {"name": "Pomarańcze", "category": "owoce"},
    {"name": "Cytryny", "category": "owoce"},
    {"name": "Gruszki Konferencja", "category": "owoce"},
    {"name": "Truskawki", "category": "owoce"},
    {"name": "Maliny", "category": "owoce"},
    {"name": "Borówki", "category": "owoce"},
    {"name": "Winogrona białe", "category": "owoce"},
    {"name": "Mango", "category": "owoce"},
    {"name": "Ananas", "category": "owoce"},
    {"name": "Kiwi", "category": "owoce"},
    {"name": "Arbuz", "category": "owoce"},
    {"name": "Śliwki węgierki", "category": "owoce"},
    {"name": "Brzoskwinie", "category": "owoce"},
    {"name": "Morele", "category": "owoce"},

    # ── Pieczywo ──────────────────────────────────────────────────────────────
    {"name": "Chleb żytni Mestemacher", "category": "pieczywo"},
    {"name": "Chleb Graham Bimbo", "category": "pieczywo"},
    {"name": "Chleb pszenny Bimbo", "category": "pieczywo"},
    {"name": "Chleb tostowy Bimbo", "category": "pieczywo"},
    {"name": "Chleb razowy z ziarnami", "category": "pieczywo"},
    {"name": "Bułki pszenne", "category": "pieczywo"},
    {"name": "Bagietka pszenna", "category": "pieczywo"},
    {"name": "Croissant Chipicao", "category": "pieczywo"},

    # ── Jajka ─────────────────────────────────────────────────────────────────
    {"name": "Jajka M 10 sztuk", "category": "jajka"},
    {"name": "Jajka L 10 sztuk", "category": "jajka"},
    {"name": "Jajka wolny wybieg 6 sztuk", "category": "jajka"},
    {"name": "Jajka ekologiczne 6 sztuk", "category": "jajka"},

    # ── Napoje ────────────────────────────────────────────────────────────────
    {"name": "Sok pomarańczowy Tymbark 1L", "category": "napoje"},
    {"name": "Sok jabłkowy Hortex 1L", "category": "napoje"},
    {"name": "Sok multiwitamina Cappy 1L", "category": "napoje"},
    {"name": "Woda Żywiec Zdrój gazowana", "category": "napoje"},
    {"name": "Woda Nałęczowianka niegazowana", "category": "napoje"},
    {"name": "Woda Cisowianka gazowana", "category": "napoje"},
    {"name": "Herbata ekspresowa Lipton", "category": "napoje"},
    {"name": "Herbata zielona Teekanne", "category": "napoje"},
    {"name": "Herbata Earl Grey Ahmad", "category": "napoje"},
    {"name": "Kawa mielona Jacobs Kronung", "category": "napoje"},
    {"name": "Kawa instant Nescafe Classic", "category": "napoje"},
    {"name": "Kawa mielona Lavazza", "category": "napoje"},
    {"name": "Coca-Cola 1,5L", "category": "napoje"},
    {"name": "Pepsi 1,5L", "category": "napoje"},
    {"name": "Sprite 1,5L", "category": "napoje"},

    # ── Przetwory / sosy ──────────────────────────────────────────────────────
    {"name": "Ketchup Pudliszki 480g", "category": "przetwory"},
    {"name": "Ketchup Heinz 570g", "category": "przetwory"},
    {"name": "Majonez Kielecki 310g", "category": "przetwory"},
    {"name": "Majonez Hellmann's 405g", "category": "przetwory"},
    {"name": "Musztarda Winiary sarepska", "category": "przetwory"},
    {"name": "Dżem truskawkowy Łowicz", "category": "przetwory"},
    {"name": "Dżem morelowy Łowicz", "category": "przetwory"},
    {"name": "Miód wielokwiatowy Pszczółka", "category": "przetwory"},
    {"name": "Pasta pomidorowa Pudliszki", "category": "przetwory"},
    {"name": "Przecier pomidorowy Mutti", "category": "przetwory"},
    {"name": "Ogórki kiszone słoik", "category": "przetwory"},
    {"name": "Ogórki konserwowe Krakus", "category": "przetwory"},
    {"name": "Kukurydza w puszce Bonduelle", "category": "przetwory"},
    {"name": "Fasola czerwona w puszce Bonduelle", "category": "przetwory"},
    {"name": "Groszek zielony w puszce Bonduelle", "category": "przetwory"},
    {"name": "Sos sojowy Kikkoman", "category": "przetwory"},

    # ── Produkty suche ────────────────────────────────────────────────────────
    {"name": "Ryż biały długoziarnisty Kupiec", "category": "inne"},
    {"name": "Ryż basmati Tilda", "category": "inne"},
    {"name": "Makaron spaghetti Lubella 500g", "category": "inne"},
    {"name": "Makaron penne Barilla 500g", "category": "inne"},
    {"name": "Makaron tagliatelle Barilla", "category": "inne"},
    {"name": "Makaron świderki Lubella", "category": "inne"},
    {"name": "Kasza gryczana Kupiec", "category": "inne"},
    {"name": "Kasza jaglana Kupiec", "category": "inne"},
    {"name": "Płatki owsiane Nestlé Chocapic", "category": "inne"},
    {"name": "Płatki górskie Dobry Start", "category": "inne"},
    {"name": "Mąka pszenna Lubella 1kg", "category": "inne"},
    {"name": "Mąka pszenna Szymanowska 1kg", "category": "inne"},
    {"name": "Cukier kryształ biały 1kg", "category": "inne"},
    {"name": "Sól kuchenna Kłodawska 1kg", "category": "inne"},
    {"name": "Olej słonecznikowy Kujawski 1L", "category": "inne"},
    {"name": "Oliwa z oliwek Bertolli 0,5L", "category": "inne"},
    {"name": "Ocet spirytusowy Roleski", "category": "inne"},
    {"name": "Bułka tarta Lubella 400g", "category": "inne"},
    {"name": "Koncentrat rosołowy Knorr", "category": "inne"},
    {"name": "Zupa pomidorowa Knorr", "category": "inne"},
    {"name": "Czekolada mleczna Milka 100g", "category": "inne"},
    {"name": "Czekolada gorzka Wedel 100g", "category": "inne"},
    {"name": "Nutella 400g", "category": "inne"},
]


def szukaj_lokalnie(query: str, n: int = 8) -> list[dict]:
    """Prefix match najpierw, potem substring — naturalna kolejność jak Google."""
    q = query.lower().strip()
    prefix = [p for p in PRODUKTY if p["name"].lower().startswith(q)]
    zawiera = [p for p in PRODUKTY if q in p["name"].lower() and not p["name"].lower().startswith(q)]
    return (prefix + zawiera)[:n]
